using System.Reflection;
using System.Text.Json;
using System.Text.Json.Serialization;
using Xunit.Sdk;

namespace Mcs.Adapters.Tests;

/// <summary>
/// The pymavlink-generated byte vectors, read once from the embedded fixture.
/// </summary>
/// <remarks>
/// <b>These bytes are the whole point of the suite.</b> A codec tested only against its own output
/// is self-consistent by construction: a wrong CRC seed, a checksum over the wrong span, and an
/// off-by-one truncation rule all cancel between an encoder and the decoder that mirrors it, and
/// every round-trip test passes. The fixture comes from pymavlink, so a test against it is a test
/// of agreement with the implementation the rest of the world flies.
/// <para>
/// Generated by <c>tools/mavlink-vectors/generate.py</c> and committed. Never hand-edited -- the
/// value of the file is entirely in its provenance, and a hand-adjusted byte is a hand-written
/// expectation wearing a generated file's authority.
/// </para>
/// </remarks>
internal static class MavlinkVectors
{
    //  Read eagerly into a static: the file is a few kilobytes, every test class needs it, and a
    //  lazy load would put a first-use cost inside whichever test happened to run first.
    internal static readonly MavlinkVectorFile File = Load();

    internal static MavlinkVector Named(string name) =>
        File.Vectors.SingleOrDefault(vector => vector.Name == name)
        ?? throw new InvalidOperationException(
            $"No vector named '{name}'. Available: {string.Join(", ", File.Vectors.Select(v => v.Name))}. "
            + "Vectors are added by editing tools/mavlink-vectors/generate.py and rerunning it.");

    internal static MavlinkStream StreamNamed(string name) =>
        File.Streams.TryGetValue(name, out MavlinkStream? stream)
            ? stream
            : throw new InvalidOperationException(
                $"No stream case named '{name}'. Available: {string.Join(", ", File.Streams.Keys)}.");

    private static MavlinkVectorFile Load()
    {
        Assembly assembly = typeof(MavlinkVectors).Assembly;

        //  Located by suffix rather than by its full resource name, which folds the directory into
        //  a dotted prefix and would break silently if the folder were ever renamed -- as a test
        //  suite that quietly stopped finding its fixture, not as a build error.
        string resourceName = assembly.GetManifestResourceNames()
            .Single(name => name.EndsWith("mavlink-v2.json", StringComparison.Ordinal));

        using System.IO.Stream stream = assembly.GetManifestResourceStream(resourceName)!;

        return JsonSerializer.Deserialize<MavlinkVectorFile>(stream, SerializerOptions)
            ?? throw new InvalidOperationException("The vector fixture deserialised to null.");
    }

    private static JsonSerializerOptions SerializerOptions => new()
    {
        PropertyNamingPolicy = JsonNamingPolicy.SnakeCaseLower,
        PropertyNameCaseInsensitive = true,
    };
}

/// <summary>The fixture's top level. Mirrors the shape <c>generate.py</c> writes.</summary>
internal sealed record MavlinkVectorFile
{
    /// <summary>The pymavlink release these bytes came from, for a failure message that can name it.</summary>
    public string PymavlinkVersion { get; init; } = string.Empty;

    public IReadOnlyList<MavlinkVector> Vectors { get; init; } = [];

    public IReadOnlyDictionary<string, MavlinkStream> Streams { get; init; } =
        new Dictionary<string, MavlinkStream>();
}

/// <summary>One message, packed by pymavlink, with the values it was packed from.</summary>
internal sealed record MavlinkVector
{
    public string Name { get; init; } = string.Empty;

    /// <summary>Why this vector is in the set. Surfaced in assertion messages.</summary>
    public string Note { get; init; } = string.Empty;

    public string Message { get; init; } = string.Empty;

    public uint MessageId { get; init; }

    /// <summary>The seed pymavlink used. The single most valuable number in the fixture.</summary>
    public byte CrcExtra { get; init; }

    /// <summary>The length byte on the wire, after truncation.</summary>
    public int PayloadLength { get; init; }

    /// <summary>The length the message definition declares, before truncation.</summary>
    public int DeclaredPayloadLength { get; init; }

    [JsonPropertyName("bytes")]
    public string Hex { get; init; } = string.Empty;

    /// <summary>
    /// The decoded field values. Unused by the framing tests and carried deliberately: the decode
    /// work reads this same fixture, and regenerating it later to add a column nobody can review is
    /// worse than emitting one field map now.
    /// </summary>
    public JsonElement Fields { get; init; }

    //  [JsonIgnore] on every derived member below. Without it the serialiser treats them as
    //  properties of the fixture and Bytes collides with Hex, which is mapped to the same "bytes"
    //  key -- a startup exception rather than a wrong answer, but only because the names happened
    //  to clash.
    [JsonIgnore]
    public byte[] Bytes => Convert.FromHexString(Hex);

    /// <summary>
    /// The payload as it appears on the wire, still truncated. Sliced out of the frame rather than
    /// carried separately in the fixture, so the two can never disagree.
    /// </summary>
    [JsonIgnore]
    public byte[] WirePayload => Bytes.AsSpan(10, PayloadLength).ToArray();

    /// <summary>The payload zero-extended back to the declared length -- what a decoder must see.</summary>
    [JsonIgnore]
    public byte[] FullPayload
    {
        get
        {
            byte[] full = new byte[DeclaredPayloadLength];
            WirePayload.CopyTo(full, 0);
            return full;
        }
    }

    public override string ToString() => Name;
}

/// <summary>A buffer, or sequence of buffers, and the frames a parser must get out of it.</summary>
internal sealed record MavlinkStream
{
    public string Note { get; init; } = string.Empty;

    /// <summary>The whole stream as one buffer. Null for cases that are defined as chunks.</summary>
    [JsonPropertyName("bytes")]
    public string? Hex { get; init; }

    /// <summary>The stream split across several reads, for the split-buffer cases.</summary>
    public IReadOnlyList<string>? Chunks { get; init; }

    /// <summary>The names of the vectors a parser must produce, in order.</summary>
    public IReadOnlyList<string> Expect { get; init; } = [];

    [JsonIgnore]
    public byte[] Bytes => Convert.FromHexString(
        Hex ?? throw new InvalidOperationException("This stream case is defined as chunks."));

    [JsonIgnore]
    public IReadOnlyList<byte[]> ChunkBytes =>
        (Chunks ?? throw new InvalidOperationException("This stream case is defined as one buffer."))
        .Select(Convert.FromHexString)
        .ToList();
}

/// <summary>
/// Feeds every frame vector into a <c>[Theory]</c>.
/// </summary>
/// <remarks>
/// A data attribute rather than a loop inside one test, so a single bad vector names itself in the
/// runner instead of failing an assertion that says only that one of six was wrong. That matters
/// most for exactly the bug this suite exists to catch: a seed correct for three messages and wrong
/// for the fourth.
/// </remarks>
internal sealed class AllVectorsAttribute : DataAttribute
{
    public override IEnumerable<object[]> GetData(MethodInfo testMethod) =>
        MavlinkVectors.File.Vectors.Select(vector => new object[] { vector });
}
