namespace Mcs.Adapters.Mavlink;

/// <summary>
/// What the link did, since the adapter started: what arrived on the socket, and what became of it
/// after framing and decoding had their say.
/// </summary>
/// <remarks>
/// The third of three counter sets, and the split between them is the split between the layers that
/// can fail independently. <see cref="MavlinkParserStatistics"/> counts bytes that were not frames;
/// <see cref="Messages.MavlinkDecoderStatistics"/> counts frames that were not usable telemetry;
/// these count what the socket and the store did either side of both. Three links in one chain, and
/// merging them would mean a rise in the total could not be attributed to any of them.
/// <para>
/// <b>What this set is for.</b> The two inner ones are silent about the two failures that look
/// identical from a console: nothing is arriving, and everything arriving is being thrown away
/// somewhere. <see cref="DatagramsReceived"/> at zero says the first; <see cref="DatagramsReceived"/>
/// climbing with <see cref="TelemetryWritten"/> flat says the second, and which of the parser's or
/// decoder's numbers moved says where.
/// </para>
/// <para>
/// Mutable and not thread-safe, matching the parser and decoder it sits with: one adapter per link,
/// one loop reading that socket, and every counter here written from that loop. Copy them out with
/// <see cref="Snapshot"/> if they are going anywhere else.
/// </para>
/// </remarks>
public sealed class MavlinkAdapterStatistics
{
    /// <summary>Gets the number of datagrams read off the socket, whatever they contained.</summary>
    /// <remarks>
    /// The first number to look at, and the one that separates "the vehicle is not talking to us"
    /// from every other explanation. Note what it is not: a datagram is not a frame in either
    /// direction -- one can carry several, and one frame can span two -- so this bearing no relation
    /// to <see cref="MavlinkParserStatistics.FramesParsed"/> is ordinary rather than a symptom.
    /// </remarks>
    public long DatagramsReceived { get; internal set; }

    /// <summary>Gets the total bytes read off the socket.</summary>
    /// <remarks>
    /// Against <see cref="DatagramsReceived"/> this gives the mean datagram size, which is how a
    /// sender that has been reconfigured -- a stream rate change, a different message set -- is
    /// noticed at all. Nothing else here would move.
    /// </remarks>
    public long BytesReceived { get; internal set; }

    /// <summary>
    /// Gets the number of socket errors the receive loop absorbed and continued through.
    /// </summary>
    /// <remarks>
    /// Absorbed, because a UDP receive can fail for reasons that have nothing to do with this
    /// station's health -- most often an ICMP rejection generated by a peer that has restarted --
    /// and a link that ends because the vehicle rebooted is a worse failure than any it reports.
    /// Counted rather than logged per occurrence for the reason the whole of this file exists: a
    /// failing link can produce these faster than a log can usefully carry them.
    /// </remarks>
    public long ReceiveErrors { get; internal set; }

    /// <summary>
    /// Gets the number of telemetry reports written to the store. <b>This is the number that means
    /// the console is being fed</b>, and the only one here that does.
    /// </summary>
    public long TelemetryWritten { get; internal set; }

    /// <summary>
    /// Gets the number of reports the store refused because the fleet was already full.
    /// </summary>
    /// <remarks>
    /// Counted, and the loop continues. The refusal is a per-vehicle fact -- a thirteenth system id
    /// on a link carrying twelve, which a router forwarding a neighbour's traffic produces without
    /// anything being wrong locally -- and ending the read loop over it would take the twelve
    /// vehicles that did fit off the console in order to report the one that did not. Anything above
    /// zero here means the map is not showing everything the link is carrying, which is the one
    /// reading of this counter, and it does not clear on its own: the store never reclaims a slot
    /// unaided.
    /// </remarks>
    public long VehiclesRejected { get; internal set; }

    /// <summary>
    /// Gets the number of frames whose decode took longer than
    /// <see cref="Mcs.Core.TelemetryIngest.RecommendedIngestBudget"/>.
    /// </summary>
    /// <remarks>
    /// The frames are still written, and written with the age they actually have -- the receipt was
    /// stamped at arrival, so a slow decode shows up here rather than as data that looks fresher
    /// than it is. That is the whole point of the two-phase boundary, and this counter is what makes
    /// the measurement visible instead of merely correct: MCS-001 budgets one second from receipt to
    /// screen, and a decode eating a twentieth of it is the first sign that work has crept in behind
    /// the socket.
    /// </remarks>
    public long IngestBudgetExceeded { get; internal set; }

    /// <summary>Returns an independent copy, safe to hand to code running on another thread.</summary>
    public MavlinkAdapterStatistics Snapshot() => new()
    {
        DatagramsReceived = DatagramsReceived,
        BytesReceived = BytesReceived,
        ReceiveErrors = ReceiveErrors,
        TelemetryWritten = TelemetryWritten,
        VehiclesRejected = VehiclesRejected,
        IngestBudgetExceeded = IngestBudgetExceeded,
    };

    public override string ToString() =>
        $"datagrams={DatagramsReceived}, bytes={BytesReceived}, receiveErrors={ReceiveErrors}, "
        + $"written={TelemetryWritten}, vehiclesRejected={VehiclesRejected}, "
        + $"slowDecodes={IngestBudgetExceeded}";
}
