#Requires -Version 5.1

<#
.SYNOPSIS
    Generates the git-ignored .env the Compose stack reads, with a random Postgres password.

.DESCRIPTION
    The repo carries this script and .env.example; it never carries a secret. Run once after
    cloning, before `docker compose up`.

    tools/bootstrap-env.sh is the same script for POSIX shells and must produce a byte-identical
    file apart from the generated password -- CI runs the .sh, this machine runs the .ps1, and a
    reviewer on either platform should be looking at the same stack. Any change here belongs there
    in the same commit.
#>

[CmdletBinding()]
param()

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

# From the script's own location, so it works from any working directory -- someone following a
# README runs it from the repo root, an IDE runs it from tools/.
$repoRoot = Split-Path -Parent $PSScriptRoot
$envPath = Join-Path $repoRoot '.env'

if (Test-Path -LiteralPath $envPath) {
    # Never overwrite. Postgres fixes the superuser password when it initialises its data directory
    # and ignores the variable on every start after that, so a regenerated password would not fail
    # loudly -- it would fail as an authentication error against a volume nothing can open any more.
    Write-Host "$envPath already exists -- leaving it alone."
    Write-Host 'Delete it and re-run to generate a new password (also delete the pgdata volume).'
    exit 0
}

# CSPRNG, not Get-Random: this value is a credential, and the cost of the correct call is one line.
# RandomNumberGenerator.Create().GetBytes() rather than the static Fill(), which does not exist on
# the .NET Framework that Windows PowerShell 5.1 runs on.
$passwordBytes = New-Object byte[] 32
$rng = [System.Security.Cryptography.RandomNumberGenerator]::Create()
try {
    $rng.GetBytes($passwordBytes)
}
finally {
    $rng.Dispose()
}

# Hex. Base64 would be shorter for the same entropy, but the .env format has no quoting and no
# escapes, and its consumers -- Compose, a shell that sources the file, Npgsql's connection-string
# parser -- each choke on a different subset of punctuation. 64 characters of [0-9a-f] pass through
# all of them unread.
$password = [System.BitConverter]::ToString($passwordBytes).Replace('-', '').ToLowerInvariant()

$content = @"
# Local configuration for the Meridian Control Station stack.
# Generated by tools/bootstrap-env -- not committed, not shared, not reused between machines.
# See .env.example for what each variable does.

POSTGRES_USER=mcs
POSTGRES_PASSWORD=$password
POSTGRES_DB=mcs

MCS_API_PORT=8081
MCS_WEB_PORT=8080
"@

# LF and no BOM, written explicitly rather than left to Set-Content's defaults. Compose reads this
# file itself instead of handing it to a shell: a CRLF line ending becomes a carriage return on the
# end of the value, and a UTF-8 BOM becomes three invisible bytes on the front of the first key. Both
# fail as an authentication error, which is a long way from the cause.
$utf8NoBom = New-Object System.Text.UTF8Encoding($false)
[System.IO.File]::WriteAllText($envPath, ($content -replace "`r`n", "`n") + "`n", $utf8NoBom)

Write-Host "Wrote $envPath with a generated POSTGRES_PASSWORD."
#  --env-file, and from the repo root. Compose looks for .env beside the compose file, not here,
#  and without the flag every ${...} in it substitutes to an empty string.
Write-Host 'Next, from the repo root:'
Write-Host '  docker compose --env-file .env -f deploy/compose/compose.yaml up --build'
