#!/usr/bin/env sh
#
# Generates the git-ignored .env the Compose stack reads, with a random Postgres password.
#
# The repo carries this script and .env.example; it never carries a secret. Run once after cloning,
# before `docker compose up`.
#
# tools/bootstrap-env.ps1 is the same script for PowerShell and must produce a byte-identical file
# apart from the generated password -- CI runs this one, a Windows machine runs that one, and a
# reviewer on either platform should be looking at the same stack. Any change here belongs there in
# the same commit.
#
# sh rather than bash: this runs on CI runners, on both testers' laptops, and potentially inside a
# container whose only shell is BusyBox ash. Nothing below needs more than POSIX.

set -eu

# From the script's own location, so it works from any working directory -- someone following a
# README runs it from the repo root, an IDE runs it from tools/. CDPATH is cleared because a cd with
# CDPATH set can land somewhere else entirely and print where it went.
script_dir=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
repo_root=$(dirname -- "$script_dir")
env_path="$repo_root/.env"

if [ -e "$env_path" ]; then
    # Never overwrite. Postgres fixes the superuser password when it initialises its data directory
    # and ignores the variable on every start after that, so a regenerated password would not fail
    # loudly -- it would fail as an authentication error against a volume nothing can open any more.
    echo "$env_path already exists -- leaving it alone."
    echo "Delete it and re-run to generate a new password (also delete the pgdata volume)."
    exit 0
fi

# Hex from a CSPRNG. Base64 would be shorter for the same entropy, but the .env format has no
# quoting and no escapes, and its consumers -- Compose, a shell that sources the file, Npgsql's
# connection-string parser -- each choke on a different subset of punctuation. 64 characters of
# [0-9a-f] pass through all of them unread.
#
# openssl is not guaranteed present, so /dev/urandom is the fallback. Both are kernel CSPRNGs;
# $RANDOM and the like are not, and this value is a credential.
if command -v openssl >/dev/null 2>&1; then
    password=$(openssl rand -hex 32)
else
    password=$(od -An -vtx1 -N32 /dev/urandom | tr -d ' \n')
fi

if [ ${#password} -ne 64 ]; then
    # Both generators above are silent on failure in at least one shell, and an empty or truncated
    # password would be written out and then spend weeks looking like a working stack.
    echo "Failed to generate a 64-character password (got ${#password} characters)." >&2
    exit 1
fi

# Created empty and locked down before the secret goes in, so the password is never briefly readable
# by every account on the machine. umask would do the same, but only if the caller's umask is what we
# assume it is.
: > "$env_path"
chmod 600 "$env_path"

# Unquoted delimiter, because $password is the one thing that expands -- nothing else below contains
# a dollar sign or a backtick.
cat > "$env_path" <<EOF
# Local configuration for the Meridian Control Station stack.
# Generated by tools/bootstrap-env -- not committed, not shared, not reused between machines.
# See .env.example for what each variable does.

POSTGRES_USER=mcs
POSTGRES_PASSWORD=$password
POSTGRES_DB=mcs

MCS_API_PORT=8081
MCS_WEB_PORT=8080
EOF

echo "Wrote $env_path with a generated POSTGRES_PASSWORD."
# --env-file, and from the repo root. Compose looks for .env beside the compose file, not here, and
# without the flag every ${...} in it substitutes to an empty string.
echo "Next, from the repo root:"
echo "  docker compose --env-file .env -f deploy/compose/compose.yaml up --build"
